---
title: "transcript_specific_counts"
author: "Florian Heigwer"
date: "4/6/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tximportData)
library(ggrepel)
library(DESeq2)
library(tidyverse)
library(patchwork)
library(ggrastr)
library(fgsea)
```


## B110 Theme

```{r theme, include=FALSE}

theme_b110 <- function(){
  theme_classic() +
  theme(
    axis.text = element_text(size = 10), 
    axis.title = element_text(size = 10),
    plot.title = element_text(size = 12,hjust = 0.5,face = "bold"),
    legend.title = element_text(size = 12),
    legend.text = element_text(size = 10),
    legend.position = "bottom"
    )
}

```

## B110 Colors

```{r colors}

sgi_blue    = '#5087C8'
sgi_yellow1 = '#F2EE35'
sgi_yellow2 = '#FED98E'
b110_grey   = '#808080'
b110_grey_light   = '#909090'
b110_transparent_black = alpha('#000000',0.5)
google_red = '#dd4b39'
google_green = '#0F9D58'
google_yellow = '#F4B400'
google_blue = '#4285F4'

```

## Read in the meta data

```{r meta_data}

raw_meta_data <- read_delim("../meta_data/19361_meta.tsv",delim = "\t")

raw_meta_data %<>% 
  filter(grepl("R1",FASTQ_FILE)) %>% 
  mutate(
    run = gsub(pattern = "(.+)_.*.fastq.gz",
               replacement = "\\1",x = FASTQ_FILE)) %>% 
  dplyr::rename(sample = SAMPLE_NAME)


```
#import the data from salmon per transcript

```{r,warning=F,message=F}

#require(tximport)
#txi <- tximport(files, type = "salmon", tx2gene = tx2gene,ignoreTxVersion = TRUE)
#names(txi)

salmon_data <- read_csv("../data/salmon_merged_transcript_counts.csv")

colnames(salmon_data) <- gsub(pattern = "(\\S+?)_R1",replacement = "\\1",x = colnames(salmon_data))

salmon_data_id2name <- read_csv("../meta_data/tx2gene.csv",col_names = c("transcript_id","gene_id","gene_name"))

```


#prepare the DESeq2 data object

```{r,warning=F,message=F}

#from the raw annotation file we need to extract the treatment and time conditions 

# in theory this could add power to the differemt block countin similar adjacent time points as replicates if this is needed

vibhu_anno <- read_delim("../meta_data/vbhu_annotations.txt",delim = "\t")

vibhu_anno %<>% 
    mutate(virus=(if_else(grepl("Cov|CoV",treatment),"Cov2","Mock")),
         drug=(if_else(grepl("8C",treatment)&!grepl("^0µM",concentration),"4µ8C",
                             if_else(grepl("4µ8C",treatment),"4µ8C",NA_character_))),
         concentration=(if_else(grepl("^0µM",concentration),NA_character_,concentration))) %>%
  mutate(sample=paste0("V",sample)) %>%
  left_join(raw_meta_data %>% dplyr::select(sample,run)) %>%
  select(sample,run,virus,drug,concentration) 

```


# design table preparation

```{r}

sampleTable_4µ8C_experiment <- vibhu_anno %>% 
                                filter(concentration %in% c("200µM",NA),drug %in% c("4µ8C",NA)) %>%
                                mutate(virus_2=if_else(is.na(concentration),
                                                       if_else(virus=="Cov2","Cov2","Mock"),"4µ8C")) %>%
                                select(sample,run,virus=virus_2) %>% 
                                as_data_frame()

rownames(sampleTable_4µ8C_experiment)<-sampleTable_4µ8C_experiment$run

```



#simple prefiltering

```{r,warning=F,message=F}

gathered_data <- salmon_data %>% gather(run,count,-transcript_id)

NUAK2_data <- gathered_data %>% left_join(sampleTable_4µ8C_experiment) %>% left_join(salmon_data_id2name) %>% filter(gene_name=="NUAK2") 

NUAK2_data %>% 
  ggplot(aes(x=virus,y=count,col=transcript_id)) + geom_boxplot() + geom_jitter()
```

